### ISSUE TITLE
[Feature Request] Sorting the search results.

### ISSUE THREAD

**Issue by iCHAIT** [dufferzafar/loki#1]
It would be nice to be able to sort the search results obtained according to their sizes, date created, names etc.
A nice way to do it would be able to click on the tab according to which I want to sort the search results.
Consider this -
When I search for *.mp3 I get a number of results with their corresponding attributes, now if I want to sort the results by say their size, then I simply click the `size tab`( as displayed on the screenshot you attached) and the results are sorted according to their sizes.

**Comment by dufferzafar** [comment]
Sorting is already present. Boo. Hoo. :stuck_out_tongue_closed_eyes:

**Comment by dufferzafar** [comment]
https://github.com/dufferzafar/loki/blob/master/loki.py#L139

**Comment by iCHAIT** [comment]
Thanks :thumbsup:
